name: Builder

on:
  workflow_dispatch:

jobs:
  ubuntu1804:
    runs-on: ubuntu-18.04

    env:
      ONNX_VERSION: 1.14.0
      ONNX_PKG_NAME: onnxruntime-1.14.0-ubuntu1804-static
      CV_VERSION: 4.6.0
      CV_PKG_NAME: opencv-4.6.0-ubuntu1804

    steps:
      # 检出代码
      - uses: actions/checkout@v6

      # 下载onnxruntime-static
      - name: download onnxruntime-static
        run: |
          cd onnxruntime-static
          wget https://github.com/RapidAI/OnnxruntimeBuilder/releases/download/${{ env.ONNX_VERSION }}/${{ env.ONNX_PKG_NAME }}.7z -O ${{ env.ONNX_PKG_NAME }}.7z
          7z x ${{ env.ONNX_PKG_NAME }}.7z -aoa

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -aoa

      # 编译
      - name: build
        run: |
          chmod a+x build-default.sh &&./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir linux-bin
          cp run-benchmark.sh linux-bin/run-benchmark.sh
          cp run-test.sh linux-bin/run-test.sh
          cp -r images linux-bin/images
          mv Linux-BIN-CPU/install/bin linux-bin/Linux-BIN-CPU
          7z a linux-bin.7z linux-bin
          mkdir linux-clib
          mv Linux-CLIB-CPU/install linux-clib/Linux-CLIB-CPU
          7z a linux-clib.7z linux-clib

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: linux-bin
          path: linux-bin.7z

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: linux-jni
          path: linux-jni.7z

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: linux-clib
          path: linux-clib.7z

  macos:
    strategy:
      fail-fast: false
      matrix:
        list:
          - { runner: macos-latest, arch: arm64 }
          - { runner: macos-13, arch: x86_64 }

    runs-on: ${{ matrix.list.runner }}

    name: macos-${{ matrix.list.arch }}

    env:
      ONNX_VERSION: 1.21.0
      ONNX_PKG_NAME: onnxruntime-v1.21.0-macos-13-${{ matrix.list.arch }}-static
      CV_VERSION: 4.11.0
      CV_PKG_NAME: opencv-4.11.0-macos-13-${{ matrix.list.arch }}

    steps:
      # 检出代码
      - uses: actions/checkout@v6

      # 下载onnxruntime-static
      - name: download onnxruntime-static
        run: |
          cd onnxruntime-static
          wget https://github.com/RapidAI/OnnxruntimeBuilder/releases/download/${{ env.ONNX_VERSION }}/${{ env.ONNX_PKG_NAME }}.7z -O ${{ env.ONNX_PKG_NAME }}.7z
          7z x ${{ env.ONNX_PKG_NAME }}.7z -omacos -aoa -y
          mv macos/${{ env.ONNX_PKG_NAME }}/* macos/
          rmdir macos/${{ env.ONNX_PKG_NAME }}

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          wget https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_PKG_NAME }}.7z -O ${{ env.CV_PKG_NAME }}.7z
          7z x ${{ env.CV_PKG_NAME }}.7z -omacos -aoa -y
          mv macos/${{ env.CV_PKG_NAME }}/* macos/
          rmdir macos/${{ env.CV_PKG_NAME }}

      # 编译
      - name: build
        run: |
          chmod a+x build-default.sh && ./build-default.sh

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir macos-bin-${{ matrix.list.arch }}
          cp run-benchmark.sh macos-bin-${{ matrix.list.arch }}/run-benchmark.sh
          cp run-test.sh macos-bin-${{ matrix.list.arch }}/run-test.sh
          cp -r images macos-bin-${{ matrix.list.arch }}/images
          mv Darwin-BIN-CPU/install/bin macos-bin-${{ matrix.list.arch }}/Darwin-BIN-CPU
          cp others/README-bin.txt macos-bin-${{ matrix.list.arch }}/README.txt
          # mkdir macos-jni
          # mv Darwin-JNI-CPU/install macos-jni/Darwin-JNI-CPU
          # 7z a macos-jni.7z macos-jni
          mkdir macos-clib-${{ matrix.list.arch }}
          mv Darwin-CLIB-CPU/install macos-clib-${{ matrix.list.arch }}/Darwin-CLIB-CPU
          cp others/README-clib.txt macos-clib-${{ matrix.list.arch }}/README.txt
          7z a macos-clib-${{ matrix.list.arch }}.7z macos-clib-${{ matrix.list.arch }}

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: macos-bin-${{ matrix.list.arch }}
          path: macos-bin-${{ matrix.list.arch }}.7z

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: macos-clib-${{ matrix.list.arch }}
          path: macos-clib-${{ matrix.list.arch }}.7z

  windows-vs2022:
    runs-on: windows-2022

    env:
      ONNX_VERSION: 1.21.0
      ONNX_X64_PKG_NAME: onnxruntime-v1.21.0-windows-vs2022-x64-static-mt
      ONNX_X86_PKG_NAME: onnxruntime-v1.21.0-windows-vs2022-x86-static-mt
      CV_VERSION: 4.11.0
      CV_X64_PKG_NAME: opencv-4.11.0-windows-vs2022-x64-mt
      CV_X86_PKG_NAME: opencv-4.11.0-windows-vs2022-x86-mt

    steps:
      # 检出代码
      - uses: actions/checkout@v6

      # 下载onnxruntime-static
      - name: download onnxruntime-static
        run: |
          cd onnxruntime-static
          Invoke-WebRequest -Uri https://github.com/RapidAI/OnnxruntimeBuilder/releases/download/${{ env.ONNX_VERSION }}/${{ env.ONNX_X64_PKG_NAME }}.7z -OutFile ${{ env.ONNX_X64_PKG_NAME }}.7z
          7z x ${{ env.ONNX_X64_PKG_NAME }}.7z -owindows-x64 -aoa -y
          mv windows-x64/${{ env.ONNX_X64_PKG_NAME }}/* windows-x64/
          rmdir windows-x64/${{ env.ONNX_X64_PKG_NAME }}
          Invoke-WebRequest -Uri https://github.com/RapidAI/OnnxruntimeBuilder/releases/download/${{ env.ONNX_VERSION }}/${{ env.ONNX_X86_PKG_NAME }}.7z -OutFile ${{ env.ONNX_X86_PKG_NAME }}.7z
          7z x ${{ env.ONNX_X86_PKG_NAME }}.7z -owindows-x86 -aoa -y
          mv windows-x86/${{ env.ONNX_X86_PKG_NAME }}/* windows-x86/
          rmdir windows-x86/${{ env.ONNX_X86_PKG_NAME }}

      # 下载opencv-static
      - name: download opencv-static
        run: |
          cd opencv-static
          Invoke-WebRequest -Uri https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_X64_PKG_NAME }}.7z -OutFile ${{ env.CV_X64_PKG_NAME }}.7z
          7z x ${{ env.CV_X64_PKG_NAME }}.7z -owindows-x64 -aoa -y
          mv windows-x64/${{ env.CV_X64_PKG_NAME }}/* windows-x64/
          rmdir windows-x64/${{ env.CV_X64_PKG_NAME }}
          Invoke-WebRequest -Uri https://github.com/RapidAI/OpenCVBuilder/releases/download/${{ env.CV_VERSION }}/${{ env.CV_X86_PKG_NAME }}.7z -OutFile ${{ env.CV_X86_PKG_NAME }}.7z
          7z x ${{ env.CV_X86_PKG_NAME }}.7z -owindows-x86 -aoa -y
          mv windows-x86/${{ env.CV_X86_PKG_NAME }}/* windows-x86/
          rmdir windows-x86/${{ env.CV_X86_PKG_NAME }}

      # 编译
      - name: build
        run: |
          ./build-default.bat

      # 使用7z压缩
      - name: 7zip
        run: |
          mkdir windows-bin
          cp run-benchmark.bat windows-bin/run-benchmark.bat
          cp run-test.bat windows-bin/run-test.bat
          cp -r images windows-bin/images
          mv win-BIN-CPU-x64/install/bin windows-bin/win-BIN-CPU-x64
          mv win-BIN-CPU-Win32/install/bin windows-bin/win-BIN-CPU-Win32
          cp others/README-bin.txt windows-bin/README.txt
          7z a windows-bin.7z windows-bin
          # mkdir windows-jni
          # mv win-JNI-CPU-x64/install windows-jni/win-JNI-CPU-x64
          # mv win-JNI-CPU-Win32/install windows-jni/win-JNI-CPU-Win32
          # 7z a windows-jni.7z windows-jni
          mkdir windows-clib
          mv win-CLIB-CPU-x64/install windows-clib/win-CLIB-CPU-x64
          mv win-CLIB-CPU-Win32/install windows-clib/win-CLIB-CPU-Win32
          cp others/README-clib.txt windows-clib/README.txt
          7z a windows-clib.7z windows-clib
          mkdir windows-cstaticlib
          mv win-CSTATICLIB-CPU-x64/install windows-cstaticlib/win-CSTATICLIB-CPU-x64
          mv win-CSTATICLIB-CPU-Win32/install windows-cstaticlib/win-CSTATICLIB-CPU-Win32
          cp others/README-clib.txt windows-cstaticlib/README.txt
          7z a windows-cstaticlib.7z windows-cstaticlib

      # 上传artifact
      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: windows-bin
          path: windows-bin.7z

      # - name: upload
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: windows-jni
      #     path: windows-jni.7z

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: windows-clib
          path: windows-clib.7z

      - name: upload-cstaticlib
        uses: actions/upload-artifact@v7
        with:
          name: windows-cstaticlib
          path: windows-cstaticlib.7z

  release:
    needs: [ ubuntu1804, macos, windows-vs2022 ]

    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v6

      # 获取所有的git log和tag
      - name: Unshallow
        run: git fetch --prune --unshallow

      # 获取git log 从 previousTag 到 lastTag
      - name: Get git log
        id: git-log
        run: |
          previousTag=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
          lastTag=$(git describe --abbrev=0 --tags)
          echo "previousTag:$previousTag ~ lastTag:$lastTag"
          log=$(git log $previousTag..$lastTag --pretty=format:'- %cd %an: %s\n' --date=format:'%Y-%m-%d %H:%M:%S')
          echo "$log"
          echo "log_state="$log"" >> $GITHUB_ENV

      # 创建Changelog文件 triggered by git tag push
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo -e '${{ env.log_state }}' > release.md

      # 下载artifact
      - name: download
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      # 查看artifact
      - name: list artifact
        run: |
          tree artifacts

      # 创建release 上传release
      - name: Create release and upload-archive
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          name: RapidOcrOnnx ${{ github.ref }}
          bodyFile: release.md
          artifacts: artifacts/*/*.7z
          allowUpdates: true
          artifactContentType: application/x-7z-compressed
          token: ${{ secrets.GITHUB_TOKEN }}
